# push-notification-service's tables (database push), for the admin only.
# Auto-generated by inspectdb against the tables that service creates at boot
# (src/notification/infrastructure/postgres-*.repository.ts):
#   * All models are managed = False and read through the "push" database
#     (config/db_router.py). push-notification-service owns these tables.
from django.db import models


class Device(models.Model):
    id = models.UUIDField(primary_key=True)
    user_id = models.TextField()
    app = models.TextField()
    token = models.TextField(unique=True)
    platform = models.TextField()
    status = models.TextField()
    last_seen_at = models.DateTimeField()
    created_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'devices'


class Notification(models.Model):
    id = models.UUIDField(primary_key=True)
    device_token = models.TextField()
    title = models.TextField()
    body = models.TextField()
    data = models.JSONField()
    status = models.TextField()
    failure_reason = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField()
    user_id = models.TextField(blank=True, null=True)
    event_id = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'notifications'
