# Generated by Django 6.0.7 on 2026-07-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verify_then_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeraccount',
            name='account_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
