# Generated by Django 6.0.7 on 2026-07-30 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_consumeraccount_account_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeraccount',
            name='currency',
            field=models.CharField(default='AED', max_length=3),
        ),
        migrations.AddField(
            model_name='consumeraccount',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='consumeraccount',
            name='is_hijab_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumeraccount',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='consumeraccount',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('push_token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'ios'), ('android', 'android'), ('web', 'web')], max_length=10)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device',
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['account', '-last_seen_at'], name='device_active_idx')],
            },
        ),
    ]
