# Generated by Django 6.0.7 on 2026-07-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_consumeraccount_currency_consumeraccount_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeraccount',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='', max_length=30),
        ),
    ]
