# Generated by Django 6.0.7 on 2026-09-11 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fix_verification_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('storefront_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favourite',
                'indexes': [models.Index(fields=['account', '-created_at'], name='favourite_account_e79fcd_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'storefront_id'), name='favourite_account_storefront_unique')],
            },
        ),
    ]
