# Generated by Django 6.0.7 on 2026-09-30 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_backfill_account_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteStylist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('staff_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_stylists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favourite_stylist',
                'indexes': [models.Index(fields=['account', '-created_at'], name='favourite_s_account_b20392_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'staff_id'), name='favourite_stylist_account_staff_unique')],
            },
        ),
    ]
