# Generated by Django 6.0.7 on 2026-10-02 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_favourite_stylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_confirmation', models.BooleanField(default=True)),
                ('appointment_reminder', models.BooleanField(default=True)),
                ('booking_changes', models.BooleanField(default=True)),
                ('special_offers', models.BooleanField(default=False)),
                ('new_salons', models.BooleanField(default=False)),
                ('loyalty', models.BooleanField(default=True)),
                ('push', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preference',
            },
        ),
    ]
