# gostyle-booking-api's tables (database gostyle_booking), for the admin only.
# Auto-generated by inspectdb against booking-api's migrations up to
# 20261007120000_start_checks_follow_the_grid, then cleaned up:
#   * All models are managed = False and read through the "booking" database
#     (config/db_router.py). booking-api (NestJS/Prisma) owns these tables.
#   * Not the platform's booking / booking_item / idempotency_key tables
#     (apps/platform_data): same names, a different database.
#   * inspectdb's comments are dropped. Its "This field type is a guess" marks
#     Postgres enums and arrays, read here as plain text.
from django.db import models


class PrismaMigrations(models.Model):
    id = models.CharField(primary_key=True, max_length=36)
    checksum = models.CharField(max_length=64)
    finished_at = models.DateTimeField(blank=True, null=True)
    migration_name = models.CharField(max_length=255)
    logs = models.TextField(blank=True, null=True)
    rolled_back_at = models.DateTimeField(blank=True, null=True)
    started_at = models.DateTimeField()
    applied_steps_count = models.IntegerField()

    class Meta:
        managed = False
        db_table = '_prisma_migrations'


class Booking(models.Model):
    id = models.UUIDField(primary_key=True)
    code = models.TextField(unique=True)
    branch_id = models.UUIDField()
    customer_id = models.UUIDField()
    status = models.TextField()
    payment_status = models.TextField()
    trading_day = models.DateField()
    start_at = models.DateTimeField()
    end_at = models.DateTimeField()
    start_minute = models.SmallIntegerField()
    duration_min = models.SmallIntegerField()
    price_fils = models.IntegerField()
    deposit_fils = models.IntegerField()
    requirement_source = models.TextField(blank=True, null=True)
    channel = models.TextField()
    move_count = models.SmallIntegerField()
    overbooked = models.BooleanField()
    overbook_reason = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    nudged_15m_at = models.DateTimeField(blank=True, null=True)
    reminded_24h_at = models.DateTimeField(blank=True, null=True)
    reminded_3h_at = models.DateTimeField(blank=True, null=True)
    link_expires_at = models.DateTimeField(blank=True, null=True)
    link_reminded_at = models.DateTimeField(blank=True, null=True)
    group_id = models.UUIDField(blank=True, null=True)
    tenant_id = models.TextField(blank=True, null=True)
    booking_type = models.TextField()
    discount_fils = models.IntegerField(blank=True, null=True)
    net_fils = models.IntegerField(blank=True, null=True)
    payment_method = models.TextField(blank=True, null=True)
    promo_code = models.TextField(blank=True, null=True)
    series_id = models.UUIDField(blank=True, null=True)
    tax_fils = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'booking'


class BookingGroup(models.Model):
    id = models.UUIDField(primary_key=True)
    branch_id = models.UUIDField()
    organiser_id = models.UUIDField()
    trading_day = models.DateField()
    target_min = models.SmallIntegerField()
    mode = models.TextField()
    arrangement = models.TextField()
    status = models.TextField()
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    active_count = models.SmallIntegerField()
    tenant_id = models.TextField(blank=True, null=True)
    source = models.TextField(blank=True, null=True)
    deposit_percent = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'booking_group'


class BookingItem(models.Model):
    id = models.UUIDField(primary_key=True)
    booking = models.ForeignKey(Booking, models.DO_NOTHING)
    service_id = models.UUIDField()
    service_name = models.TextField()
    resource_type = models.TextField()
    required_skill = models.TextField()
    price_fils = models.IntegerField()
    duration_min = models.SmallIntegerField()
    position = models.SmallIntegerField()
    staff_id = models.UUIDField()
    source = models.TextField(blank=True, null=True, db_comment='Which catalogue priced this line: platform (gRPC), fixture (static slug map), or mixed (a group row summing both). NULL means the row predates this column -- not that the source is unknown-but-recordable.')

    class Meta:
        managed = False
        db_table = 'booking_item'
        unique_together = (('booking', 'position'),)


class BookingProduct(models.Model):
    id = models.UUIDField(primary_key=True)
    booking = models.ForeignKey(Booking, models.DO_NOTHING)
    product_id = models.UUIDField()
    product_name = models.TextField()
    price_fils = models.IntegerField()
    quantity = models.SmallIntegerField()
    position = models.SmallIntegerField()
    created_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'booking_product'
        unique_together = (('booking', 'position'),)


class BookingSeries(models.Model):
    id = models.UUIDField(primary_key=True)
    branch_id = models.UUIDField()
    customer_id = models.UUIDField()
    anchor_day = models.DateField()
    start_min = models.SmallIntegerField()
    pattern = models.TextField()
    weekdays = models.TextField(blank=True, null=True)
    interval_weeks = models.SmallIntegerField(blank=True, null=True)
    day_of_month = models.SmallIntegerField(blank=True, null=True)
    custom_dates = models.TextField(blank=True, null=True)
    end_kind = models.TextField()
    end_date = models.DateField(blank=True, null=True)
    end_count = models.SmallIntegerField(blank=True, null=True)
    auto_confirm_rule = models.TextField()
    status = models.TextField()
    service_id = models.UUIDField()
    preferred_staff_id = models.UUIDField(blank=True, null=True)
    baseline_price_fils = models.IntegerField()
    grandfathered = models.BooleanField()
    materialised_through = models.DateField(blank=True, null=True)
    course_total_net_fils = models.IntegerField(blank=True, null=True)
    course_visits = models.SmallIntegerField(blank=True, null=True)
    course_drawn = models.SmallIntegerField()
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    tenant_id = models.TextField(blank=True, null=True)
    source = models.TextField(blank=True, null=True)
    frequency = models.TextField(blank=True, null=True)
    service_ids = models.TextField(blank=True, null=True)
    payment_plan = models.TextField(blank=True, null=True)
    paused_until = models.DateField(blank=True, null=True)
    pause_reason = models.TextField(blank=True, null=True)
    pause_note = models.TextField(blank=True, null=True)
    miss_streak_after = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'booking_series'


class BookingStatusHistory(models.Model):
    id = models.UUIDField(primary_key=True)
    booking = models.ForeignKey(Booking, models.DO_NOTHING)
    from_status = models.TextField(blank=True, null=True)
    to_status = models.TextField()
    reason = models.TextField(blank=True, null=True)
    metadata = models.JSONField(blank=True, null=True)
    actor_kind = models.TextField()
    actor_id = models.UUIDField(blank=True, null=True)
    created_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'booking_status_history'


class DepositLedger(models.Model):
    id = models.UUIDField(primary_key=True)
    booking = models.ForeignKey(Booking, models.DO_NOTHING)
    entry_type = models.TextField()
    amount_fils = models.IntegerField()
    rail = models.TextField(blank=True, null=True)
    gateway_ref = models.TextField(unique=True, blank=True, null=True)
    pos_transaction_id = models.TextField(blank=True, null=True)
    linked_entry = models.ForeignKey('self', models.DO_NOTHING, blank=True, null=True)
    reason = models.TextField(blank=True, null=True)
    actor_kind = models.TextField()
    actor_id = models.UUIDField(blank=True, null=True)
    created_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'deposit_ledger'


class EventOutbox(models.Model):
    id = models.UUIDField(primary_key=True)
    aggregate_type = models.TextField()
    aggregate_id = models.UUIDField()
    event_type = models.TextField()
    payload = models.JSONField()
    created_at = models.DateTimeField()
    published_at = models.DateTimeField(blank=True, null=True)
    attempts = models.SmallIntegerField()
    last_error = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'event_outbox'


class GroupParticipant(models.Model):
    id = models.UUIDField(primary_key=True)
    group = models.ForeignKey(BookingGroup, models.DO_NOTHING)
    customer_id = models.UUIDField(blank=True, null=True)
    guest_name = models.TextField(blank=True, null=True)
    booking_id = models.UUIDField(unique=True, blank=True, null=True)
    share_fils = models.IntegerField(blank=True, null=True)
    position = models.SmallIntegerField()
    created_at = models.DateTimeField()
    age_group = models.TextField(blank=True, null=True)
    client_ref = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'group_participant'
        unique_together = (('group', 'position'),)


class Hold(models.Model):
    id = models.UUIDField(primary_key=True)
    branch_id = models.UUIDField()
    customer_id = models.UUIDField(blank=True, null=True)
    trading_day = models.DateField()
    feasibility_token = models.TextField()
    expires_at = models.DateTimeField()
    created_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'hold'


class IdempotencyKey(models.Model):
    key = models.TextField(primary_key=True)
    operation = models.TextField()
    request_hash = models.TextField()
    response_status = models.SmallIntegerField(blank=True, null=True)
    response_body = models.JSONField(blank=True, null=True)
    booking = models.ForeignKey(Booking, models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField()
    expires_at = models.DateTimeField()
    customer_id = models.UUIDField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'idempotency_key'


class NotificationDelivery(models.Model):
    id = models.UUIDField(primary_key=True)
    source_event_id = models.UUIDField()
    channel = models.TextField()
    event_type = models.TextField()
    booking = models.ForeignKey(Booking, models.DO_NOTHING)
    customer_id = models.UUIDField()
    scheduled_for = models.DateTimeField()
    expires_at = models.DateTimeField()
    status = models.TextField()
    attempts = models.SmallIntegerField()
    next_attempt_at = models.DateTimeField()
    last_error = models.TextField(blank=True, null=True)
    skip_reason = models.TextField(blank=True, null=True)
    provider_ref = models.TextField(blank=True, null=True)
    sent_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'notification_delivery'
        unique_together = (('source_event_id', 'channel'),)


class ResourceReservation(models.Model):
    id = models.UUIDField(primary_key=True)
    booking_item = models.ForeignKey(BookingItem, models.DO_NOTHING, blank=True, null=True)
    hold = models.ForeignKey(Hold, models.DO_NOTHING, blank=True, null=True)
    branch_id = models.UUIDField()
    resource_type = models.TextField()
    resource_unit_id = models.UUIDField(blank=True, null=True)
    trading_day = models.DateField()
    start_at = models.DateTimeField()
    end_at = models.DateTimeField()
    start_minute = models.SmallIntegerField()
    duration_min = models.SmallIntegerField()
    blocking = models.BooleanField()

    class Meta:
        managed = False
        db_table = 'resource_reservation'


class RosterChange(models.Model):
    id = models.UUIDField(primary_key=True)
    branch_id = models.UUIDField()
    trading_day = models.DateField()
    kind = models.TextField()
    staff_id = models.UUIDField(blank=True, null=True)
    resource_type = models.TextField(blank=True, null=True)
    reason = models.TextField()
    committed_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    tenant_id = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'roster_change'


class RosterChangeItem(models.Model):
    id = models.UUIDField(primary_key=True)
    change = models.ForeignKey(RosterChange, models.DO_NOTHING)
    booking_id = models.UUIDField()
    booking_code = models.TextField()
    state = models.TextField()
    rung = models.TextField(blank=True, null=True)
    proposal = models.JSONField(blank=True, null=True)
    resolved_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'roster_change_item'
        unique_together = (('change', 'booking_id'),)


class SeriesOccurrence(models.Model):
    id = models.UUIDField(primary_key=True)
    series = models.ForeignKey(BookingSeries, models.DO_NOTHING)
    index = models.SmallIntegerField()
    planned_day = models.DateField()
    planned_start_min = models.SmallIntegerField()
    moved_from_day_of_month = models.SmallIntegerField(blank=True, null=True)
    state = models.TextField()
    booking_id = models.UUIDField(unique=True, blank=True, null=True)
    alternatives = models.JSONField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'series_occurrence'
        unique_together = (('series', 'index'),)


class StaffReservation(models.Model):
    id = models.UUIDField(primary_key=True)
    booking_item = models.ForeignKey(BookingItem, models.DO_NOTHING, blank=True, null=True)
    hold = models.ForeignKey(Hold, models.DO_NOTHING, blank=True, null=True)
    branch_id = models.UUIDField()
    staff_id = models.UUIDField()
    trading_day = models.DateField()
    kind = models.TextField()
    start_at = models.DateTimeField()
    end_at = models.DateTimeField()
    start_minute = models.SmallIntegerField()
    duration_min = models.SmallIntegerField()
    blocking = models.BooleanField()
    claim_post_min = models.SmallIntegerField()
    claim_pre_min = models.SmallIntegerField()
    processing_from_min = models.SmallIntegerField(blank=True, null=True)
    processing_to_min = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'staff_reservation'


class WaitlistEntry(models.Model):
    id = models.UUIDField(primary_key=True)
    branch_id = models.UUIDField()
    customer_id = models.UUIDField()
    service_id = models.TextField()
    trading_day = models.DateField()
    window_from_min = models.SmallIntegerField()
    window_to_min = models.SmallIntegerField()
    preferred_staff_id = models.UUIDField(blank=True, null=True)
    status = models.TextField()
    decline_count = models.SmallIntegerField()
    declined_codes = models.TextField(blank=True, null=True)
    offered_booking_code = models.TextField(blank=True, null=True)
    offer_expires_at = models.DateTimeField(blank=True, null=True)
    joined_at = models.DateTimeField()
    tenant_id = models.TextField(blank=True, null=True)
    offered_duration_min = models.SmallIntegerField(blank=True, null=True)
    offered_staff_id = models.UUIDField(blank=True, null=True)
    offered_start_min = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'waitlist_entry'


class WalkInEntry(models.Model):
    id = models.UUIDField(primary_key=True)
    branch_id = models.UUIDField()
    trading_day = models.DateField()
    customer_id = models.UUIDField(blank=True, null=True)
    guest_name = models.TextField(blank=True, null=True)
    service_ids = models.TextField(blank=True, null=True)
    duration_min = models.SmallIntegerField()
    status = models.TextField()
    booking_id = models.UUIDField(unique=True, blank=True, null=True)
    joined_min = models.SmallIntegerField()
    joined_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    hold_id = models.UUIDField(blank=True, null=True)
    tenant_id = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'walk_in_entry'
