# Generated by Django 6.0.7 on 2026-08-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('gents', 'Gents'), ('ladies', 'Ladies'), ('unisex', 'Unisex')], max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('open_now', models.BooleanField(default=True)),
                ('hours', models.CharField(max_length=64)),
                ('logo', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
