# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0fgostyle.auth.v1\"&\n\x15VerifyConsumerRequest\x12\r\n\x05token\x18\x01 \x01(\t\"N\n\x16VerifyConsumerResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x13\n\x0b\x63onsumer_id\x18\x02 \x01(\t\x12\x10\n\x08verified\x18\x03 \x01(\x08\x32q\n\x0c\x43onsumerAuth\x12\x61\n\x0eVerifyConsumer\x12&.gostyle.auth.v1.VerifyConsumerRequest\x1a\'.gostyle.auth.v1.VerifyConsumerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYCONSUMERREQUEST']._serialized_start=31
  _globals['_VERIFYCONSUMERREQUEST']._serialized_end=69
  _globals['_VERIFYCONSUMERRESPONSE']._serialized_start=71
  _globals['_VERIFYCONSUMERRESPONSE']._serialized_end=149
  _globals['_CONSUMERAUTH']._serialized_start=151
  _globals['_CONSUMERAUTH']._serialized_end=264
# @@protoc_insertion_point(module_scope)
