# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: consumer_directory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'consumer_directory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63onsumer_directory.proto\x12\x13gostyle.consumer.v1\"0\n\x19GetConsumerContactRequest\x12\x13\n\x0b\x63onsumer_id\x18\x01 \x01(\t\"\xb5\x01\n\x0f\x43onsumerContact\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x13\n\x0b\x63onsumer_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x16\n\x0e\x65mail_verified\x18\x04 \x01(\x08\x12\x11\n\tfull_name\x18\x05 \x01(\t\x12\x10\n\x08language\x18\x06 \x01(\t\x12\x1c\n\x14\x61ppointment_reminder\x18\x07 \x01(\x08\x12\x14\n\x0cpush_enabled\x18\x08 \x01(\x08\x32\x7f\n\x11\x43onsumerDirectory\x12j\n\x12GetConsumerContact\x12..gostyle.consumer.v1.GetConsumerContactRequest\x1a$.gostyle.consumer.v1.ConsumerContactb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consumer_directory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCONSUMERCONTACTREQUEST']._serialized_start=49
  _globals['_GETCONSUMERCONTACTREQUEST']._serialized_end=97
  _globals['_CONSUMERCONTACT']._serialized_start=100
  _globals['_CONSUMERCONTACT']._serialized_end=281
  _globals['_CONSUMERDIRECTORY']._serialized_start=283
  _globals['_CONSUMERDIRECTORY']._serialized_end=410
# @@protoc_insertion_point(module_scope)
