# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import consumer_directory_pb2 as consumer__directory__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in consumer_directory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConsumerDirectoryStub:
    """How to reach a customer, for the services that send them messages.

    Served by gostyle-customer-api beside ConsumerAuth, on the same :50051.
    The caller presents the shared internal key as gRPC metadata
    `x-internal-key`; without it the call is refused (UNAUTHENTICATED),
    because the answer is a person's email address.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConsumerContact = channel.unary_unary(
                '/gostyle.consumer.v1.ConsumerDirectory/GetConsumerContact',
                request_serializer=consumer__directory__pb2.GetConsumerContactRequest.SerializeToString,
                response_deserializer=consumer__directory__pb2.ConsumerContact.FromString,
                _registered_method=True)


class ConsumerDirectoryServicer:
    """How to reach a customer, for the services that send them messages.

    Served by gostyle-customer-api beside ConsumerAuth, on the same :50051.
    The caller presents the shared internal key as gRPC metadata
    `x-internal-key`; without it the call is refused (UNAUTHENTICATED),
    because the answer is a person's email address.
    """

    def GetConsumerContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsumerDirectoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConsumerContact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsumerContact,
                    request_deserializer=consumer__directory__pb2.GetConsumerContactRequest.FromString,
                    response_serializer=consumer__directory__pb2.ConsumerContact.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gostyle.consumer.v1.ConsumerDirectory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gostyle.consumer.v1.ConsumerDirectory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsumerDirectory:
    """How to reach a customer, for the services that send them messages.

    Served by gostyle-customer-api beside ConsumerAuth, on the same :50051.
    The caller presents the shared internal key as gRPC metadata
    `x-internal-key`; without it the call is refused (UNAUTHENTICATED),
    because the answer is a person's email address.
    """

    @staticmethod
    def GetConsumerContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gostyle.consumer.v1.ConsumerDirectory/GetConsumerContact',
            consumer__directory__pb2.GetConsumerContactRequest.SerializeToString,
            consumer__directory__pb2.ConsumerContact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
