# Generated by Django 6.0.7 on 2026-09-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='mime_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('PDF', 'Pdf'), ('DOCUMENT', 'Document')], max_length=20),
        ),
    ]
