# Generated by Django 6.0.7 on 2026-10-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('app', models.TextField()),
                ('token', models.TextField(unique=True)),
                ('platform', models.TextField()),
                ('status', models.TextField()),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('device_token', models.TextField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('data', models.JSONField()),
                ('status', models.TextField()),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('user_id', models.TextField(blank=True, null=True)),
                ('event_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
    ]
