# review-service's tables (database review), for the admin only.
# Auto-generated by inspectdb against review-service's migrations up to
# 20261008130000_reviews, then cleaned up:
#   * All models are managed = False and read through the "review" database
#     (config/db_router.py). review-service (NestJS/Prisma) owns these tables.
#   * Models using CompositePrimaryKey are kept for ORM access. The Django
#     admin does not support composite primary keys, so each one has a
#     list_only *Rows twin at the end of this file, which is what the admin
#     shows (config/read_only_admin.py).
#   * inspectdb's comments are dropped. Its "This field type is a guess" marks
#     Postgres enums, read here as plain text.
from django.db import models


class PrismaMigrations(models.Model):
    id = models.CharField(primary_key=True, max_length=36)
    checksum = models.CharField(max_length=64)
    finished_at = models.DateTimeField(blank=True, null=True)
    migration_name = models.CharField(max_length=255)
    logs = models.TextField(blank=True, null=True)
    rolled_back_at = models.DateTimeField(blank=True, null=True)
    started_at = models.DateTimeField()
    applied_steps_count = models.IntegerField()

    class Meta:
        managed = False
        db_table = '_prisma_migrations'


class InboxEvent(models.Model):
    pk = models.CompositePrimaryKey('source', 'event_id')
    source = models.TextField()
    event_id = models.TextField()
    event_type = models.TextField()
    tenant_id = models.UUIDField(blank=True, null=True)
    outcome = models.TextField()
    received_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'inbox_event'


class OutboxEvent(models.Model):
    id = models.UUIDField(primary_key=True)
    tenant_id = models.UUIDField()
    aggregate_type = models.TextField()
    aggregate_id = models.UUIDField()
    event_type = models.TextField()
    payload = models.JSONField()
    created_at = models.DateTimeField()
    published_at = models.DateTimeField(blank=True, null=True)
    attempts = models.SmallIntegerField()
    last_error = models.TextField(blank=True, null=True)
    next_attempt_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'outbox_event'


class RatingSummary(models.Model):
    pk = models.CompositePrimaryKey('subject_type', 'subject_id')
    subject_type = models.TextField()
    subject_id = models.UUIDField()
    tenant_id = models.UUIDField()
    branch_id = models.UUIDField()
    review_count = models.IntegerField()
    rating_sum = models.IntegerField()
    star_1 = models.IntegerField()
    star_2 = models.IntegerField()
    star_3 = models.IntegerField()
    star_4 = models.IntegerField()
    star_5 = models.IntegerField()
    count_en = models.IntegerField()
    count_ar = models.IntegerField()
    version = models.BigIntegerField()
    updated_at = models.DateTimeField()
    last_recomputed_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'rating_summary'


class Review(models.Model):
    id = models.UUIDField(primary_key=True)
    tenant_id = models.UUIDField()
    storefront_id = models.UUIDField()
    branch_id = models.UUIDField()
    booking_source = models.TextField()
    booking_id = models.UUIDField()
    invite = models.OneToOneField('ReviewInvite', models.DO_NOTHING)
    customer_id = models.UUIDField(blank=True, null=True)
    rating = models.SmallIntegerField()
    comment = models.TextField(blank=True, null=True)
    language = models.TextField()
    author_display_name = models.TextField()
    state = models.TextField()
    moderated_by_id = models.UUIDField(blank=True, null=True)
    moderated_at = models.DateTimeField(blank=True, null=True)
    moderation_note = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'review'
        unique_together = (('booking_source', 'booking_id'),)


class ReviewInvite(models.Model):
    id = models.UUIDField(primary_key=True)
    tenant_id = models.UUIDField()
    storefront_id = models.UUIDField()
    branch_id = models.UUIDField()
    booking_source = models.TextField()
    booking_id = models.UUIDField()
    token_hash = models.TextField(unique=True)
    expires_at = models.DateTimeField()
    used_at = models.DateTimeField(blank=True, null=True)
    customer_id = models.UUIDField(blank=True, null=True)
    salon_name = models.TextField(blank=True, null=True)
    storefront_slug = models.TextField(blank=True, null=True)
    locale = models.TextField(blank=True, null=True)
    send_status = models.TextField()
    send_attempts = models.SmallIntegerField()
    sent_at = models.DateTimeField(blank=True, null=True)
    last_send_error = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'review_invite'
        unique_together = (('booking_source', 'booking_id'),)


class ReviewReply(models.Model):
    id = models.UUIDField(primary_key=True)
    tenant_id = models.UUIDField()
    review = models.OneToOneField(Review, models.DO_NOTHING)
    body = models.TextField()
    author_id = models.UUIDField()
    edited_by_id = models.UUIDField(blank=True, null=True)
    edited_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'review_reply'


class ReviewReport(models.Model):
    id = models.UUIDField(primary_key=True)
    tenant_id = models.UUIDField()
    review = models.OneToOneField(Review, models.DO_NOTHING)
    reason = models.TextField()
    note = models.TextField(blank=True, null=True)
    status = models.TextField()
    reported_by_id = models.UUIDField()
    resolved_by_id = models.UUIDField(blank=True, null=True)
    resolved_at = models.DateTimeField(blank=True, null=True)
    resolution_note = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'review_report'


# The admin's view of the tables above with a primary key of several columns
# (config/read_only_admin.py). The first key column stands in as the primary
# key, so these are for the admin list only, never for the ORM.


class InboxEventRows(models.Model):
    list_only = True

    source = models.TextField(primary_key=True)
    event_id = models.TextField()
    event_type = models.TextField()
    tenant_id = models.UUIDField(blank=True, null=True)
    outcome = models.TextField()
    received_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'inbox_event'
        verbose_name = 'inbox event'


class RatingSummaryRows(models.Model):
    list_only = True

    subject_type = models.TextField(primary_key=True)
    subject_id = models.UUIDField()
    tenant_id = models.UUIDField()
    branch_id = models.UUIDField()
    review_count = models.IntegerField()
    rating_sum = models.IntegerField()
    star_1 = models.IntegerField()
    star_2 = models.IntegerField()
    star_3 = models.IntegerField()
    star_4 = models.IntegerField()
    star_5 = models.IntegerField()
    count_en = models.IntegerField()
    count_ar = models.IntegerField()
    version = models.BigIntegerField()
    updated_at = models.DateTimeField()
    last_recomputed_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'rating_summary'
        verbose_name = 'rating summary'

